# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20151222_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='league',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
