# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_team_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='abbr',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
