# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('abbr', models.CharField(max_length=10)),
                ('sport_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='sport',
            field=models.ForeignKey(default='baseball', on_delete=django.db.models.deletion.CASCADE, to='api.Sport'),
            preserve_default=False,
        ),
    ]
