# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_team_abbr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='salary',
        ),
        migrations.AddField(
            model_name='athlete',
            name='age',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='athlete',
            name='number',
            field=models.CharField(max_length=10),
        ),
    ]
