# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 01:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athlete',
            old_name='postion',
            new_name='position',
        ),
    ]
